export enum UserRole {
  None = -1,
  Client,
  ExtendedClient,
  Minor,
  Administrator,
  ExtendedProfessional,
  PSP,
  Reseller,
  Distributeur,
  ClientNotBanked,
  ProCashier = 12,
  Professional = 15,
  BOCustomerRelationship,
  CallCenterCustomerRelationship,
  BOManager,
  ChiefOperatingOfficer,
  TechnicalDirector,
  OperationManager,
  MarketingManager,
  BOAdministrator,
  FluxManager,
  PermanentController,
  OAuthClient,
  AdministratorPro,
  UserPool,
  AdministratorThirdParty,
  ProOperatorIzly,
  ManagerIzly,
  RegionalAdministratorIzly,
  NationalAdministratorIzly,
  CustomerCashAccount,
  CashingPointAggregate,
  SpacePartnerSuperAdmin = 36,
  CommunicationRegional = 38,
  CommunicationNational
}
